Hw10 program optimization
truep/golang-otus-hw pull request #10
Opened 2023-10-29 17:37 UTC by truep

## Домашнее задание №10 «Оптимизация программы»
Benchmark command:
``` go test -bench=BenchmarkGetDomainStat -benchmem -benchtime 10s -count 10 ```

Benchstat comparison results:
```
goos: linux
goarch: amd64
pkg: github.com/truep/golan-otus-hw/hw10_program_optimization
cpu: AMD Ryzen 7 5800H with Radeon Graphics         
                 │   old.out   │               new.out                │
                 │   sec/op    │   sec/op     vs base                 │
GetDomainStat-16   1.282m ± 6%   3.882m ± 2%  +202.91% (p=0.000 n=10)
                 │   old.out    │                 new.out                 │
                 │     B/op     │     B/op       vs base                  │
GetDomainStat-16   35.17Ki ± 5%   900.42Ki ± 0%  +2460.09% (p=0.000 n=10)
                 │  old.out   │              new.out               │
                 │ allocs/op  │ allocs/op   vs base                │
GetDomainStat-16   348.0 ± 5%   101.0 ± 5%  -70.98% (p=0.000 n=10)
```

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я написал бенчмарк и приложил результаты benchstat.

### Критерии оценки
- [ ] Пайплайн зелёный и нет попытки «обмануть» систему - 4 балла
- [ ] Добавлены юнит-тесты - до 3 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2023-10-29 18:46 UTC, vladislavmass requested changes
Хорошее начало, но код не проходит следующий тест-кейс `{"Id":6,"Name":"Janice Rose","Username":"KeithHart","Email":"null.com@Linktype.aza","Phone":"146-91-01","Password":"acSBF5","Address":"Russell Trail 61"}` делается поиск по домену com. Для решения этой проблемы рекомендую заменить регулярное выражение на `strings.HasSuffix` это будет лучше и в плане производительности.

Также рекомендую подумать что будет с данным кодом если в дотаяете будет более 100 000 элементов

2023-10-29 18:46 UTC, vladislavmass commented on hw10_program_optimization/stats.go
>  type users [100_000]User
А точно стоит хранить 100 000 юзеров просто для того, что бы разбить код на 2 функции? Или лучше объединить getUsers и  countDomains, тем самым избежав создание массива и сэкономив память

2023-10-29 18:49 UTC, truep commented on hw10_program_optimization/stats.go
>  type users [100_000]User
Что-то я не подумал, что по ТЗ нельзя менять только одну функцию. Подумаю и переделаю.

2023-10-31 19:45 UTC, hungry-honeybadger requested changes
Уже стало лучше, но потенциальная паника мешает принять работу

2023-10-31 19:45 UTC, hungry-honeybadger commented on hw10_program_optimization/stats.go
>  type User struct {
Создавать всю структуру ради одного поля не самая хорошая конечно идея

2023-10-31 19:45 UTC, hungry-honeybadger commented on hw10_program_optimization/stats.go
> +			if matched := strings.HasSuffix(user.Email, suffix); matched {
Тут все таки лучше бы было `if strings.HasSuffix(user.Email, suffix) {`

2023-10-31 19:45 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +				num := countResults[resultString]
Эти 3 строки меняются без проблем на `countResults[resultString]++`

2023-10-31 19:45 UTC, vladislavmass commented on hw10_program_optimization/stats.go
> +				resultString := strings.ToLower(strings.SplitN(user.Email, "@", 2)[1])
Не учтен вариант что в поле email может не быть символа @  и тогда мы получим выход за границы массива

2023-11-01 14:11 UTC, truep commented on hw10_program_optimization/stats.go
>  type User struct {
Убрал и для решил использовать fastjson, стало даже немного быстрее.

2023-11-01 14:12 UTC, truep commented on hw10_program_optimization/stats.go
> +				resultString := strings.ToLower(strings.SplitN(user.Email, "@", 2)[1])
Поправил.

2023-11-01 14:12 UTC, truep commented on hw10_program_optimization/stats.go
> +				num := countResults[resultString]
Спасибо. Глаз замылился, вижу, что что-то не то, и никак не вижу что. Поправил.

2023-11-01 19:38 UTC, vladislavmass approved these changes
Отлично. Принято

2023-11-02 05:30 UTC, merged