hw02 is completed
truep/golang-otus-hw pull request #2
Opened 2023-08-10 07:22 UTC by truep

* написал решение задачи
* добавил кейсов в тесты

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-08-10 07:47 UTC, vladislavmass approved these changes
Хорошая работа. Принято. 10/10

2023-08-10 07:47 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +		if index == len(runePacked)-1 {
Данный код лучше вынести за пределы цикла for. Так как делать проверку на условие, которое может сработать всего 1 раз и мы знаем когда это не самый оптимальный вариант.

2023-08-10 07:47 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	runePacked := []rune(packed)
Копирование строки в слайс рун не самый оптимальный вариант.

2023-08-10 07:47 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	ErrInvalidNumber = errors.New("invalid number")
Не вижу тестов на данную функциональность.

2023-08-10 08:03 UTC, truep commented on hw02_unpack_string/unpack.go
> +	ErrInvalidNumber = errors.New("invalid number")
Не придумал. =( Так как выше мы проверяем `IsNumber(nextRune)` - и я вообще не уверен, что эта часть кода достижима...

2023-08-10 08:33 UTC, vladislavmass commented on hw02_unpack_string/unpack.go
> +	ErrInvalidNumber = errors.New("invalid number")
Можно попробовать сделать тест кейс вот с этим '১'. Это бенгальская цифра. Ну либо как вариант игнорировать эту ошибку

2023-08-12 21:21 UTC, truep commented on hw02_unpack_string/unpack.go
> +	ErrInvalidNumber = errors.New("invalid number")
Спасибо. Добавил кейс

2023-08-13 05:40 UTC, vladislavmass requested changes
Зачем обязательно смотреть на следующий символ, что если помнить прошлый? Ну и 2 тест кейса который не проходят.
1) Строка, которая должна приводит к ошибке так как ничего не экранирует `qw\`
2) {input: `qwe\\\\`, expected: `qwe\\`},

2023-08-23 05:54 UTC, vladislavmass approved these changes
Интересное решение. Интересно было бы увидеть такое решение со звездочкой. Смущает то, что мы считали 2 символа и при этом на след круге мы опять читаем второй символ только уже как первый. Может стоит переиспользовать  `nextRune`?

2023-08-23 08:22 UTC, merged