Hw04 lru cache
truep/golang-otus-hw pull request #4
Opened 2023-08-25 13:22 UTC by truep

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-08-25 14:03 UTC, vladislavmass requested changes
Хорошее начало. Кэш написан правильно и потокобезопасен. Но не реализован 2 связный список.

2023-08-25 14:03 UTC, hungry-honeybadger commented on hw04_lru_cache/cache.go
> +	for lc.queue.Len() > 0 {
В данном случае удаление будет идти за O(n). Что бы получить O(1) надо просто пересоздать обе структуры

2023-08-26 14:57 UTC, truep commented on hw04_lru_cache/cache.go
> +	for lc.queue.Len() > 0 {
Переделал,но возник вопрос, а GC удалит старые список и карту? Не будет ли копиться это в памяти?

2023-08-26 15:43 UTC, vladislavmass commented on hw04_lru_cache/cache.go
> +	for lc.queue.Len() > 0 {
Если во время сборки мусора эти структуры не будут доступны из кода, то да удалит.

2023-08-27 04:35 UTC, vladislavmass approved these changes
Отлично. Работа принята. 10/10. Круто что написано много тестов на разные кейсы

2023-08-27 04:35 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.len == 0 {
По сути это оверинженеринг. При длине листа в 0 элементов `l.head` должен быть равен `nil` и поэтому никакого смысла делать отдельную обработку этого кейса нет

2023-08-27 04:35 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	if l.len == 0 {
По сути это оверинженеринг. При длине листа в 0 элементов `l.tail` должен быть равен `nil` и поэтому никакого смысла делать отдельную обработку этого кейса нет

2023-08-27 04:35 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	case l.Front() == l.Back():
Очень странно выглядит это конструкция. С учетом того, что если у нас всего 1 элемент то у него `Next` и так `nil, как и `Prev`. Поэтому никаких особых обработок тут не надо

2023-08-27 08:57 UTC, truep commented on hw04_lru_cache/list.go
> +	case l.Front() == l.Back():
Это же сравнение head и tail списка, при одном элементе они не будут nil и как раз будут равны и указывать на этот элемент. С таким кейсом после switch выходит бессмысленные операции над элементом списка
```	
    i.Next = nil
    i.Prev = nil
```
но иначе пришлось бы в каждом case писать.

2023-08-27 09:00 UTC, merged

2023-08-27 09:16 UTC, vladislavmass commented on hw04_lru_cache/list.go
> +	case l.Front() == l.Back():
Так если у нас 1 элемент, то они уже`nil`. И при `if else` это бы без проблем сработало. Только и проверки были бы не то, что этот element равен `head` или tail, а проверка бы шла за счет того, что у элемента следующий и предыдущий nil. Но вариация тоже имеет место быть