hw_06 is completed
truep/golang-otus-hw pull request #6
Opened 2023-09-21 06:10 UTC by truep

## Домашнее задание №6 «Пайплайн»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - pipeline.go ~55 строк

### Критерии оценки
- [ ] CI-пайплайн зелёный - 5 баллов
- [ ] Добавлены новые юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2023-09-21 07:24 UTC, vladislavmass requested changes
Хорошее начало, но есть потенциальный лок. А также хотелось бы увидеть больше тестов.

2023-09-21 07:24 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +			ch <- v
Предположим что один поток зашел в эту точку, а stage еще работает. Пока мы ждали что stage закончит работу прилетел Done и следующий такой обработчик закрылся. По итогу мы зависнем на этой строчке кода, и stage тоже зависнет на ожидание и это очень плохо. Надо это как то исправлять

2023-09-21 14:57 UTC, truep commented on hw06_pipeline_execution/pipeline.go
> +			ch <- v
Кажется, что это что-то прям из ряда вон или я просто не могу придумать такой тест-кейс. 
Думается мне, что может помочь буферизированный канал? Но как это проверить, даже не знаю.

2023-09-21 15:10 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +			ch <- v
Буферезированный канал не поможет. Он также может забиться. А поможет тут еще 1 select. И в defer было бы не плохо считать из канала перед его закрытием. Такой тест кейс можно создать только через подбор таймингов. В этом и сложность.

2023-09-22 15:49 UTC, truep commented on hw06_pipeline_execution/pipeline.go
> +			ch <- v
Про селект я кажется  понял. Про вычитывать перед закрытием не очень. Как я понял, это чтобы никакие лишние данные после остановки не попадали в следующий сейдж... Но что-то Прям с трудом даётся понять как это можно сделать нормально.

2023-09-23 04:28 UTC, vladislavmass commented on hw06_pipeline_execution/pipeline.go
> +			ch <- v
Немного не так. Вычитывание перед закрытием нужно для того, что бы предыдущий stage не завис на записи в канал из которого мы читаем.
```

2023-09-23 08:54 UTC, truep commented on hw06_pipeline_execution/pipeline.go
> +			ch <- v
Если я всё верно понял, то будет так. Как ещё можно вычитать из канала, ничего не делая с данными, я не смог придумать, поэтому пометил пустой блок //nolint иначе линтер ругается.

2023-09-28 03:50 UTC, vladislavmass approved these changes
Отличная работа. Принято. Но хотелось бы видеть больше тестов

2023-09-28 06:10 UTC, merged