wip: hw08 started
truep/golang-otus-hw pull request #8
Opened 2023-10-12 19:44 UTC by truep

## Домашнее задание №8 «Утилита envdir»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-10-14 15:22 UTC, vladislavmass requested changes
Хорошее начало, но есть небольшая недоработка

2023-10-14 15:22 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +				ev[file.Name()] = EnvValue{
А что будет если в файле будут только символы, которые мы по тз должны удалить?

2023-10-14 16:41 UTC, truep commented on hw08_envdir_tool/env_reader.go
> +				ev[file.Name()] = EnvValue{
Как я это понимаю:
1. мы считаем, что после удаление пробелов и табуляций, файл пустой => нужно удалять переменную окружения
2. мы считаем, файл ненулевой длины изначально => после удаления нужно заменить значение существующей переменной или установить с пустым значением.

Исходя из тз: `файл полностью пустой (длина - 0 байт)`, я склоняюсь ко второму варианту. Дописал к нему тест. Работает, как ожидается.

2023-10-15 10:48 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +				ev[file.Name()] = EnvValue{
Правильным будет ситуация 1.  Не установлено это означает что os.LookupEnv в exists вернет false и то, что в файле есть проблем или табуляци это не значит что их установил пользователь. Например при использование vs code можно настроить так, что всегда будет 1 пустая строка, или одно время wsl страдал такой историей

2023-10-15 13:30 UTC, truep commented on hw08_envdir_tool/env_reader.go
> +				ev[file.Name()] = EnvValue{
кажется, что при таком подходе мы и EMPTY из примера будем удалять, а не обнулять значение.

2023-10-16 04:08 UTC, vladislavmass commented on hw08_envdir_tool/env_reader.go
> +				ev[file.Name()] = EnvValue{
Ок. Согласен с вашим вариантом.  Просто есть понимание что на практике это не всегда хороший вариант. Например лет 5 назад одна популярная IDE создавала файлы начинающиеся с CRLF и тогда по размеру он уже был бы не пустой для нашей задачи

2023-10-16 04:08 UTC, vladislavmass approved these changes
Хорошая работа. Принято

2023-10-16 08:03 UTC, merged